import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { Montserrat, Roboto_Mono } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-montserrat',
});

const roboto_mono = Roboto_Mono({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto-mono',
});

export const metadata = {
    title: 'Website',
    description: 'Generated by create next app + tailwind',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${montserrat.variable} ${roboto_mono.variable} bg-light text-dark`}
            >
                <Navbar />
                <div className="px-32 py-8">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
